# Generated by Django 2.1 on 2019-05-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('AppID', models.CharField(default=1, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('Cp_name', models.CharField(max_length=20)),
                ('Cp_tel', models.CharField(max_length=20)),
                ('Cp_rela', models.CharField(max_length=20)),
                ('Ap_stat', models.CharField(blank=1, max_length=20)),
                ('Ap_stat1', models.CharField(blank=1, max_length=20)),
                ('Remarks', models.TextField()),
                ('Time_ar', models.CharField(blank=1, default=None, max_length=20)),
                ('Time_er', models.CharField(max_length=20)),
                ('Time_eo', models.CharField(max_length=20)),
                ('wcsy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BedId', models.CharField(max_length=30)),
                ('BedState', models.CharField(max_length=20)),
                ('BedStart', models.CharField(default='null', max_length=20)),
                ('BedEnd', models.CharField(default='null', max_length=20)),
                ('CustomerId', models.CharField(default='null', max_length=30)),
                ('Details', models.CharField(default='null', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Check_out',
            fields=[
                ('customerID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('check_out_type', models.CharField(max_length=20)),
                ('check_out_reason', models.TextField()),
                ('check_out_time', models.DateField()),
                ('check_out_state', models.BooleanField()),
                ('time', models.DateField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CitemNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=12)),
                ('ItemNum', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('nation', models.CharField(max_length=20)),
                ('btype', models.CharField(max_length=4)),
                ('ID_number', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('marrige', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('phonenum1', models.CharField(max_length=11)),
                ('phonenum2', models.CharField(blank=True, max_length=11, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('state_1', models.BooleanField()),
                ('state_2', models.BooleanField()),
                ('nursing', models.CharField(blank=True, max_length=10, null=True)),
                ('bedID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.Bed')),
            ],
        ),
        migrations.CreateModel(
            name='MealCalendarInfo',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('mealID', models.CharField(max_length=6)),
                ('offerDay', models.CharField(max_length=6)),
                ('offerTime', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MealManageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerDay', models.CharField(max_length=6)),
                ('offerTime', models.CharField(max_length=6)),
                ('remarks', models.CharField(max_length=50)),
                ('clientID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='MealStorageInfo',
            fields=[
                ('mealID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('mealType', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('offerWeek', models.CharField(max_length=20)),
                ('muslim', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NursingItemInfo',
            fields=[
                ('itemID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('price', models.IntegerField()),
                ('addedService', models.BooleanField()),
                ('details', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NursingNoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('remarks', models.CharField(max_length=50)),
                ('clientID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.Customer')),
                ('itemID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.NursingItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='NursingTypeInfo',
            fields=[
                ('typeID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('positionID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTime', models.DateTimeField()),
                ('recordType', models.CharField(max_length=12)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('clientID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.Customer')),
                ('itemID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.NursingItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomId', models.CharField(max_length=30)),
                ('RoomArea', models.IntegerField()),
                ('RoomState', models.CharField(max_length=20)),
                ('RoomFunction', models.CharField(max_length=20)),
                ('RoomBedNum', models.IntegerField()),
                ('RoomRank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR_id', models.CharField(max_length=30)),
                ('SR_rank', models.CharField(max_length=30)),
                ('SR_standard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.IntegerField()),
                ('status', models.CharField(max_length=8)),
                ('clientID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.Customer')),
                ('itemID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.NursingItemInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('customerId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=12)),
                ('staffName', models.CharField(max_length=12)),
                ('staffId', models.CharField(max_length=12)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('staffID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('employeeDate', models.DateField()),
                ('jobTitle', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=40)),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.PositionInfo', to_field='position')),
            ],
        ),
        migrations.CreateModel(
            name='StaffTypeInfo',
            fields=[
                ('typeID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('staffType', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
                ('position', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='staffType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.StaffTypeInfo', to_field='staffType'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.UserInfo'),
        ),
        migrations.AddField(
            model_name='recordinfo',
            name='operatorID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.UserInfo'),
        ),
        migrations.AddField(
            model_name='nursingnoteinfo',
            name='operatorID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.StaffInfo'),
        ),
        migrations.AddField(
            model_name='nursingiteminfo',
            name='itemType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.NursingTypeInfo'),
        ),
        migrations.AddField(
            model_name='mealmanageinfo',
            name='mealID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ManageModels.MealStorageInfo'),
        ),
        migrations.AddField(
            model_name='bed',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageModels.Room'),
        ),
    ]
